#!/bin/bash
export IFS=$'\n'
DATE=`date +%Y_%m_%d`

argv=("$@")
CMDNAME=`basename $0`

## https://qiita.com/hit/items/e95298f689a1ee70ae4a                                                                                                                                                               
_pcnt=`pgrep -fo ${CMDNAME} | wc -l`               
if [ ${_pcnt} -gt 1 ]; then                        
	echo "This script has been running now. proc : ${_pcnt}"
	exit 1                                           
fi

##
NICE=19
THREADS=$(( (`cat /proc/cpuinfo | grep processor | wc -l` +1) / 4))
PRESET_V=veryslow
AUDIO_BITRATE=256k

##
if [ $# -eq 0 ]; then
    echo "Usage : ${CMDNAME} [-n nicevalue] [-t thread count] [-p video preset value] [-b audio bitrate] <dirname>"
    exit 1
fi

## https://qiita.com/b4b4r07/items/dcd6be0bb9c9185475bb#%E3%81%84%E3%81%A3%E3%81%9D%E8%87%AA%E5%89%8D%E3%81%A7%E8%A7%A3%E6%9E%90%E3%81%97%E3%81%A1%E3%82%83%E3%81%86
for OPT in "$@"
do
        case "$OPT" in
                '-n'|'--nice')
                        NICE=$OPTARG
			shift 2
                ;;
                '-t'|'--threads')
                        THREADS=$OPTARG
			shift 2
                ;;
                '-p'|'--preset')
                        PRESET_V=$OPTARG
			shift 2
                ;;
                '-b'|'--bitrate')
                        AUDIO_BITRATE=$OPTARG
			shift 2
                ;;
                : )
                ;;
                \? )
                ;;
        esac
done

##
EXTLIST=`cat /etc/mime.types | grep -v "#" | grep video | grep -v mp4 | grep -v mkv | tr "\t" " " | tr -s " " | cut -d " " -f 2 | grep -v "/" | sort | uniq`
EXTLIST+=(
"mov"
".avi"
"avi.mp4"
"wmv.mp4"
"flv.mp4"
"mpeg"
"mpg"
"flv"
"rmvb"
"wmv"
"m4a"
"avi"
"ts")
EXTLIST+=($(echo "${EXTLIST[*]^^}" ))
EXTLIST=($(echo "${EXTLIST[*]}" | sort | uniq))

##
for ARG_DIR in ${argv}
do
	DIR=$ARG_DIR
	for EXT in ${EXTLIST[@]}
	do
		for FILENAME in `find "${DIR}" -name "*.${EXT}" | sort`
		do
			echo "${FILENAME}"
			nice -n ${NICE} ffmpeg -hide_banner -y -i "${FILENAME}" -movflags +faststart -codec:v libx264 -preset:v ${PRESET_V} -threads ${THREADS} -acodec aac -b:a ${AUDIO_BITRATE} "${FILENAME%.${EXT}}.mp4" || continue
      			rm -f "${FILENAME}"
		done
	done
done
