#!/bin/bash
export IFS=$'\n'
DATE=`date +%Y_%m_%d`

argv=("$@")
CMDNAME=`basename $0`

if [ $# -eq 0 ]; then
    echo "Usage : ${CMDNAME} [dirname]"
    exit 1
fi

## https://qiita.com/hit/items/e95298f689a1ee70ae4a                                                                                                                                                               
_pcnt=`pgrep -fo ${CMDNAME} | wc -l`               
if [ ${_pcnt} -gt 1 ]; then                        
	echo "This script has been running now. proc : ${_pcnt}"
	exit 1                                           
fi

##
NICE=19
THREADS=$(( (`cat /proc/cpuinfo | grep processor | wc -l` +1) / 2))
PRESET_V=veryslow
AUDIO_BITRATE=256k


## http://takuya-1st.hatenablog.jp/entry/2015/12/24/234238
while getopts ":nice:threads:preset_v:audio_bitrate" OPT ; do
        case $OPT in
                nice)
                        NICE=$OPTARG
                ;;
                threads)
                        THREADS=$OPTARG
                ;;
                preset_v)
                        PRESET_V=$OPTARG
                ;;
                audio_bitrate)
                        AUDIO_BITRATE=$OPTARG
                ;;
                : )
                ;;
                \? )
                ;;
        esac
done

##
EXTLIST=`cat /etc/mime.types | grep -v "#" | grep video | grep -v mp4 | tr "\t" " " | tr -s " " | cut -d " " -f 2 | grep -v "/" | sort | uniq`
EXTLIST+=(
"mov"
"mkv"
"..avi"
"avi.mp4"
"wmv.mp4"
"flv.mp4"
"mpeg"
"mpg"
"flv"
"rmvb"
"wmv"
"M4A"
"avi"
"ts")
EXTLIST=($(echo "${EXTLIST[*]}" | sort | uniq))

##
for ARG_DIR in ${argv}
do
	DIR=$ARG_DIR
	for EXT in ${EXTLIST[@]}
	do
		for FILENAME in `find "${DIR}" -name "*.${EXT}" | sort`
		do
			echo "${FILENAME}"
			nice -n ${NICE} ffmpeg -hide_banner -y -i "${FILENAME}" -movflags +faststart -codec:v libx264 -preset:v ${PRESET_V} -threads ${THREADS} -acodec aac -b:a ${AUDIO_BITRATE} "${FILENAME%.${EXT}}.mp4" || continue
      			rm -f "${FILENAME}"
		done
	done
done
